// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/campaign": {
            "post": {
                "description": "Send campaign messages via email/WhatsApp/Telegram",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Campaign"
                ],
                "summary": "Start a messaging campaign",
                "parameters": [
                    {
                        "description": "Campaign Request",
                        "name": "campaign",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/campaign.CampaignRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Campaign started",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/checkdb": {
            "post": {
                "description": "Checks only server connectivity (host + port + credentials). Does NOT verify database existence.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Database"
                ],
                "summary": "Check Database Server Connection",
                "parameters": [
                    {
                        "description": "Database Authentication Details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DBAuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Connection successful",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/getconnection": {
            "get": {
                "description": "Returns a simple JSON response to confirm that the API service is up.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Check API Connection",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/gpthandler": {
            "post": {
                "description": "Send prompt and get AI response",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GPT"
                ],
                "summary": "Chat with GPT",
                "parameters": [
                    {
                        "description": "Chat Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/gpt.ChatBotRequest"
                        }
                    }
                ],
                "responses": {
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "campaign.CampaignRequest": {
            "type": "object",
            "required": [
                "channel",
                "emails"
            ],
            "properties": {
                "channel": {
                    "description": "Channel type: email, whatsapp, telegram",
                    "type": "string",
                    "enum": [
                        "email",
                        "whatsapp",
                        "telegram"
                    ]
                },
                "emails": {
                    "description": "Emails to send (for email campaigns)",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/email.EmailInput"
                    }
                }
            }
        },
        "email.EmailInput": {
            "type": "object",
            "required": [
                "body",
                "from",
                "subject",
                "to"
            ],
            "properties": {
                "bcc": {
                    "description": "BCC (optional, must be valid email if provided)",
                    "type": "string"
                },
                "body": {
                    "description": "Body (required)",
                    "type": "string"
                },
                "cc": {
                    "description": "CC (optional, must be valid email if provided)",
                    "type": "string"
                },
                "from": {
                    "description": "From email (required, must be valid email)",
                    "type": "string"
                },
                "subject": {
                    "description": "Subject (required)",
                    "type": "string"
                },
                "to": {
                    "description": "To recipient (required, must be valid email)",
                    "type": "string"
                }
            }
        },
        "gpt.ChatBotRequest": {
            "type": "object",
            "properties": {
                "agent": {
                    "type": "string",
                    "example": "You are a helpful assistant"
                },
                "model": {
                    "type": "string",
                    "example": "gpt-4o-mini"
                },
                "openAi_ApI_key": {
                    "type": "string",
                    "example": "sk-1234567890abcdef"
                },
                "prompt": {
                    "type": "string",
                    "example": "Explain Golang in simple terms"
                }
            }
        },
        "models.DBAuthRequest": {
            "type": "object",
            "required": [
                "host",
                "password",
                "port",
                "type",
                "username"
            ],
            "properties": {
                "host": {
                    "type": "string",
                    "example": "localhost"
                },
                "password": {
                    "type": "string",
                    "example": "123456"
                },
                "port": {
                    "type": "string",
                    "example": "3306"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "mysql",
                        "postgres"
                    ],
                    "example": "mysql"
                },
                "username": {
                    "type": "string",
                    "example": "root"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "SDT API Services",
	Description:      "Simple API service with a health check endpoint.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
